const mongoose = require("mongoose");
const { StudentModel } = require("../models/StudentsModel"); // Adjust the path as needed
require("dotenv").config();

const students = [
  {
    email: "rdowney0@issuu.com",
    studentName: "Rhett",
    studentId: "21695-315",
    studentClass: "Czech",
    password: 'bW8%LA2cAk"',
  },
  {
    email: "adawtrey1@earthlink.net",
    studentName: "Ab",
    studentId: "54868-5024",
    studentClass: "Icelandic",
    password: "mI9#LG82Sc&#!+MB",
  },
  {
    email: "gpauwel2@usgs.gov",
    studentName: "Gerome",
    studentId: "36987-2372",
    studentClass: "Kyrgyz",
    password: "sJ7<pf%'0`Ar2",
  },
  {
    email: "kbett3@bing.com",
    studentName: "Kaylil",
    studentId: "36987-2812",
    studentClass: "Icelandic",
    password: "oB6\\%Sm(",
  },
  {
    email: "xmallaby4@java.com",
    studentName: "Xenia",
    studentId: "52959-077",
    studentClass: "Zulu",
    password: "lG3?#xrUDHkp*K",
  },
  {
    email: "gdemalchar5@phpbb.com",
    studentName: "Gabe",
    studentId: "59390-177",
    studentClass: "Tamil",
    password: "dY2)V&5k+w{",
  },
  {
    email: "phulcoop6@bandcamp.com",
    studentName: "Purcell",
    studentId: "61727-341",
    studentClass: "Nepali",
    password: "pI6?,u3@8Tn",
  },
  {
    email: "cdewbury7@blog.com",
    studentName: "Celle",
    studentId: "67345-0012",
    studentClass: "Belarusian",
    password: "aL0/&Pfkf{?cGz",
  },
  {
    email: "aboulter8@usda.gov",
    studentName: "Aurlie",
    studentId: "53208-545",
    studentClass: "Dzongkha",
    password: "rZ1}Fah|",
  },
  {
    email: "bclacson9@exblog.jp",
    studentName: "Bibbye",
    studentId: "0832-1121",
    studentClass: "Greek",
    password: 'iH0"VR&c_!h7Z',
  },
  {
    email: "sroucha@amazon.de",
    studentName: "Sinclair",
    studentId: "44004-321",
    studentClass: "Spanish",
    password: "eR4~_S/j_",
  },
  {
    email: "mtremayneb@europa.eu",
    studentName: "Madelin",
    studentId: "55910-703",
    studentClass: "Hindi",
    password: "eT1)xMt{,4|evTH",
  },
  {
    email: "adigiorgioc@youtube.com",
    studentName: "Avie",
    studentId: "55154-6815",
    studentClass: "Tamil",
    password: "pY8$1X9{4>F,5TZ",
  },
  {
    email: "gnestorukd@moonfruit.com",
    studentName: "Gwyn",
    studentId: "42333-101",
    studentClass: "Telugu",
    password: "yD6,3Jug@t",
  },
  {
    email: "gnavarijoe@ezinearticles.com",
    studentName: "Gilli",
    studentId: "53345-004",
    studentClass: "Ndebele",
    password: "qT2&fSZVijo",
  },
  {
    email: "jrickcordf@wordpress.com",
    studentName: "Jacquenetta",
    studentId: "63029-201",
    studentClass: "Punjabi",
    password: "fG0)D!3ns0t",
  },
  {
    email: "cpracyg@va.gov",
    studentName: "Caprice",
    studentId: "63629-2817",
    studentClass: "Portuguese",
    password: "cT5.xwZFz$",
  },
  {
    email: "kperaccoh@usa.gov",
    studentName: "Kayla",
    studentId: "69244-3001",
    studentClass: "Kurdish",
    password: "cH4'sOa~&1",
  },
  {
    email: "jvardyi@networkadvertising.org",
    studentName: "Jacklin",
    studentId: "36987-2417",
    studentClass: "Albanian",
    password: "bX0&Qd1!9vMycRE",
  },
  {
    email: "gdonaghyj@reddit.com",
    studentName: "Georgeanna",
    studentId: "63029-602",
    studentClass: "West Frisian",
    password: "bI9!0>vljPBw`$",
  },
  {
    email: "aspurdlek@joomla.org",
    studentName: "Alaster",
    studentId: "37808-192",
    studentClass: "German",
    password: "zB6((snfW",
  },
  {
    email: "dfaichniel@ftc.gov",
    studentName: "Dee",
    studentId: "68428-733",
    studentClass: "Ndebele",
    password: "dV4=(}1i",
  },
  {
    email: "cmaciejakm@blogs.com",
    studentName: "Collie",
    studentId: "17856-1206",
    studentClass: "Danish",
    password: "vU2+7%y$#<c6#?",
  },
  {
    email: "jvanderstraatenn@eventbrite.com",
    studentName: "Johnath",
    studentId: "57664-117",
    studentClass: "Luxembourgish",
    password: 'lX4`sND"u4Cm?4I',
  },
  {
    email: "msoutho@irs.gov",
    studentName: "Margarita",
    studentId: "52533-024",
    studentClass: "Montenegrin",
    password: "zV0)Ld2tq",
  },
  {
    email: "pgoburnp@ycombinator.com",
    studentName: "Pauline",
    studentId: "0093-7224",
    studentClass: "Tajik",
    password: "vA2!n~OI~iqge>Y1",
  },
  {
    email: "dwhatmoughq@intel.com",
    studentName: "Derrek",
    studentId: "63868-104",
    studentClass: "Ndebele",
    password: "uI3+tVD%hbxG\\v",
  },
  {
    email: "hdarrowr@nydailynews.com",
    studentName: "Haily",
    studentId: "54868-5903",
    studentClass: "Guaraní",
    password: "fZ5~3FY~IZ|2_{",
  },
  {
    email: "drobards@wordpress.org",
    studentName: "Devina",
    studentId: "55648-711",
    studentClass: "Kazakh",
    password: "aI8/+`U4",
  },
  {
    email: "gshawyerst@freewebs.com",
    studentName: "Gwenny",
    studentId: "63629-2935",
    studentClass: "West Frisian",
    password: "vL9.y.Ix8",
  },
  {
    email: "wdemitrisu@nba.com",
    studentName: "Woody",
    studentId: "51060-073",
    studentClass: "Lithuanian",
    password: "lZ5#Q1h@?&AT",
  },
  {
    email: "rstihlv@nhs.uk",
    studentName: "Reynold",
    studentId: "49738-600",
    studentClass: "Romanian",
    password: 'nG7`+y+"V',
  },
  {
    email: "dpatrichew@w3.org",
    studentName: "Dollie",
    studentId: "49967-713",
    studentClass: "Papiamento",
    password: "rA2(29Hv0",
  },
  {
    email: "cmundyx@paypal.com",
    studentName: "Carol",
    studentId: "50181-0016",
    studentClass: "Indonesian",
    password: "bG6!A>ei}V~)v",
  },
  {
    email: "mpeplayy@cpanel.net",
    studentName: "Mair",
    studentId: "49715-004",
    studentClass: "Polish",
    password: "wL3#c=y@F",
  },
  {
    email: "aengelmannz@mozilla.org",
    studentName: "Anjanette",
    studentId: "0268-1265",
    studentClass: "Swedish",
    password: "dF3+>dj+L",
  },
  {
    email: "jkean10@eventbrite.com",
    studentName: "Jae",
    studentId: "10424-167",
    studentClass: "Malayalam",
    password: "iE0|FQ.|*xh2/W!F",
  },
  {
    email: "jhalegarth11@networkadvertising.org",
    studentName: "Janella",
    studentId: "36987-2173",
    studentClass: "Gujarati",
    password: "sJ3'5X{})%",
  },
  {
    email: "ckimber12@feedburner.com",
    studentName: "Celine",
    studentId: "21695-251",
    studentClass: "Papiamento",
    password: "uW5@p@%(?t",
  },
  {
    email: "esutworth13@vkontakte.ru",
    studentName: "Elsa",
    studentId: "36987-2776",
    studentClass: "Persian",
    password: "fQ9|B.D/)*{Y&q",
  },
  {
    email: "rcoggon14@chron.com",
    studentName: "Rene",
    studentId: "64679-669",
    studentClass: "Bosnian",
    password: "tS0+PLI&u",
  },
  {
    email: "bgaynes15@salon.com",
    studentName: "Brett",
    studentId: "24236-453",
    studentClass: "Punjabi",
    password: "hP8/kx$~*3",
  },
  {
    email: "jbolter16@cbc.ca",
    studentName: "Jerrold",
    studentId: "62037-863",
    studentClass: "Danish",
    password: "nW8?~/UuZ",
  },
  {
    email: "tbirt17@ihg.com",
    studentName: "Tobey",
    studentId: "49738-335",
    studentClass: "Aymara",
    password: "xT6.q,8F2+4FaEk'",
  },
  {
    email: "dbuck18@webs.com",
    studentName: "Durant",
    studentId: "62592-720",
    studentClass: "Italian",
    password: "hH6(>~&}%o!~",
  },
  {
    email: "abaruch19@discuz.net",
    studentName: "Annadiana",
    studentId: "53346-1368",
    studentClass: "Burmese",
    password: "fQ4#3Vg)b='H\\f",
  },
  {
    email: "sblue1a@msu.edu",
    studentName: "Syd",
    studentId: "58517-060",
    studentClass: "Tetum",
    password: 'nZ9"Jn8}=Jo!Q',
  },
  {
    email: "rcoolson1b@loc.gov",
    studentName: "Roselia",
    studentId: "0268-6191",
    studentClass: "Bislama",
    password: "nL2~8H!r",
  },
  {
    email: "nbourgeois1c@tamu.edu",
    studentName: "Noach",
    studentId: "16729-277",
    studentClass: "Tamil",
    password: "wT2'j4UY6H",
  },
  {
    email: "tstockford1d@skype.com",
    studentName: "Todd",
    studentId: "54569-1104",
    studentClass: "Burmese",
    password: 'fR2"P!c06M)9',
  },
  {
    email: "dfillery1e@indiegogo.com",
    studentName: "Dimitri",
    studentId: "49260-716",
    studentClass: "Hebrew",
    password: 'fZ5"7BX<m',
  },
  {
    email: "cflavelle1f@elpais.com",
    studentName: "Casey",
    studentId: "55910-294",
    studentClass: "Georgian",
    password: "kT0+sg>s'",
  },
  {
    email: "wbrierton1g@zimbio.com",
    studentName: "Walker",
    studentId: "55154-1486",
    studentClass: "Icelandic",
    password: "kL5|Qzd\\1S5u8i",
  },
  {
    email: "dwhipp1h@domainmarket.com",
    studentName: "Derry",
    studentId: "21695-594",
    studentClass: "Indonesian",
    password: "oZ8)>1DDjw5!)1",
  },
  {
    email: "daked1i@illinois.edu",
    studentName: "Dave",
    studentId: "24385-963",
    studentClass: "Arabic",
    password: "xX6`+y!9Y?",
  },
  {
    email: "tplitz1j@buzzfeed.com",
    studentName: "Thomasa",
    studentId: "55154-6649",
    studentClass: "Filipino",
    password: "wD0+Hz)cUo4!",
  },
  {
    email: "jlundon1k@bbc.co.uk",
    studentName: "Junina",
    studentId: "0004-0098",
    studentClass: "Swahili",
    password: "iH9!vbU4XFt(",
  },
  {
    email: "abergeau1l@patch.com",
    studentName: "Arlyne",
    studentId: "68180-892",
    studentClass: "Bengali",
    password: "pP9*DZT|vvn",
  },
  {
    email: "vserrurier1m@live.com",
    studentName: "Vilma",
    studentId: "48951-9019",
    studentClass: "Kannada",
    password: "sF7\\'E.9.",
  },
  {
    email: "erustidge1n@seattletimes.com",
    studentName: "Elysia",
    studentId: "0187-1613",
    studentClass: "Czech",
    password: "cP3?J|kPuf,4Vi4",
  },
  {
    email: "gharrald1o@vistaprint.com",
    studentName: "Georgi",
    studentId: "54868-4624",
    studentClass: "Gagauz",
    password: "zV3&~i'kg$",
  },
  {
    email: "ceverton1p@nba.com",
    studentName: "Cleve",
    studentId: "43269-699",
    studentClass: "Kurdish",
    password: "hN9~,K95@VXu8F",
  },
  {
    email: "npochon1q@domainmarket.com",
    studentName: "Novelia",
    studentId: "55111-526",
    studentClass: "Mongolian",
    password: 'nN8!r>`qs"Pi=s\\$',
  },
  {
    email: "jburnsall1r@un.org",
    studentName: "Jaymie",
    studentId: "63481-816",
    studentClass: "West Frisian",
    password: "qP3{#dh0",
  },
  {
    email: "vdawidsohn1s@4shared.com",
    studentName: "Vicky",
    studentId: "0409-1463",
    studentClass: "Thai",
    password: "yD7+/Wn}R",
  },
  {
    email: "hwyant1t@about.com",
    studentName: "Hasty",
    studentId: "10819-6005",
    studentClass: "Estonian",
    password: "nD2=AKs<w1",
  },
  {
    email: "wkeay1u@twitter.com",
    studentName: "Wendell",
    studentId: "44567-507",
    studentClass: "Quechua",
    password: "nE2+S72RP<32AcD",
  },
  {
    email: "wgiovannardi1v@springer.com",
    studentName: "Warden",
    studentId: "51655-102",
    studentClass: "Croatian",
    password: "eT3+BcI3",
  },
  {
    email: "rzannutti1w@ocn.ne.jp",
    studentName: "Robinett",
    studentId: "0378-3855",
    studentClass: "Tok Pisin",
    password: "wW4`Nuh)|t_",
  },
  {
    email: "ggritsunov1x@utexas.edu",
    studentName: "Griswold",
    studentId: "13537-010",
    studentClass: "Tswana",
    password: "dN0\\9iDXX(",
  },
  {
    email: "cmersh1y@fotki.com",
    studentName: "Celisse",
    studentId: "0268-1151",
    studentClass: "Pashto",
    password: 'pO0&"lD|7|',
  },
  {
    email: "bletcher1z@networksolutions.com",
    studentName: "Brandyn",
    studentId: "66435-302",
    studentClass: "Tswana",
    password: "aS4)+`Uta/lRf",
  },
  {
    email: "egosker20@archive.org",
    studentName: "Ethelbert",
    studentId: "52125-210",
    studentClass: "Oriya",
    password: "wS1!cj+YE'S}7h/",
  },
  {
    email: "bmorigan21@cafepress.com",
    studentName: "Betteann",
    studentId: "51621-037",
    studentClass: "Czech",
    password: "xY0{\\3E&TJP&RNK4",
  },
  {
    email: "ecrass22@hibu.com",
    studentName: "Ezechiel",
    studentId: "0409-1135",
    studentClass: "German",
    password: "yC4/eGu%",
  },
  {
    email: "lneem23@hostgator.com",
    studentName: "Loralyn",
    studentId: "11701-052",
    studentClass: "Spanish",
    password: "dJ0$wpkF",
  },
  {
    email: "kneilly24@pbs.org",
    studentName: "Killie",
    studentId: "57337-057",
    studentClass: "Northern Sotho",
    password: "dA8{*jQ+U",
  },
  {
    email: "rruckledge25@studiopress.com",
    studentName: "Reider",
    studentId: "49349-521",
    studentClass: "Dari",
    password: "sU7$~h2c>EI@2}",
  },
  {
    email: "dcallicott26@example.com",
    studentName: "Doralin",
    studentId: "30142-049",
    studentClass: "Georgian",
    password: "wF3=ByF>TCa=bUh3",
  },
  {
    email: "mfreddi27@about.com",
    studentName: "Merrile",
    studentId: "37000-452",
    studentClass: "Danish",
    password: "xL6'h*0Yb,iq",
  },
  {
    email: "lwithinshaw28@un.org",
    studentName: "Livvie",
    studentId: "65649-301",
    studentClass: "Korean",
    password: "oJ3=&nr+1o\\Ct",
  },
  {
    email: "oaulsford29@is.gd",
    studentName: "Oswell",
    studentId: "65923-009",
    studentClass: "Tswana",
    password: "aL6+Ny1X_}mo*+",
  },
  {
    email: "osinclar2a@ebay.com",
    studentName: "Obie",
    studentId: "50436-9787",
    studentClass: "Romanian",
    password: "jW5$hw.`cO/P",
  },
  {
    email: "lvasyatkin2b@tumblr.com",
    studentName: "Lorettalorna",
    studentId: "49738-544",
    studentClass: "Somali",
    password: "jI3,0D=vakS",
  },
  {
    email: "fdregan2c@geocities.com",
    studentName: "Flint",
    studentId: "61715-111",
    studentClass: "Malay",
    password: "uA5)fCTwdG{9HQ",
  },
  {
    email: "mchenery2d@slashdot.org",
    studentName: "Maryrose",
    studentId: "58668-1381",
    studentClass: "Estonian",
    password: "wH8`Rj7%rh,ya~",
  },
  {
    email: "hmesnard2e@plala.or.jp",
    studentName: "Herve",
    studentId: "43742-0016",
    studentClass: "Filipino",
    password: "gD0|&I`!d((z",
  },
  {
    email: "dhaquin2f@gov.uk",
    studentName: "Don",
    studentId: "64613-0456",
    studentClass: "Pashto",
    password: 'mA0"@7(H%Uc`>Y',
  },
  {
    email: "scorbally2g@engadget.com",
    studentName: "Sumner",
    studentId: "98132-716",
    studentClass: "Belarusian",
    password: "eJ1|fWWyR9t/",
  },
  {
    email: "twaind2h@sina.com.cn",
    studentName: "Tedra",
    studentId: "42315-002",
    studentClass: "Khmer",
    password: "uB4<7nIa?b5a%}",
  },
  {
    email: "wbawcock2i@mit.edu",
    studentName: "Whitney",
    studentId: "54868-4070",
    studentClass: "Latvian",
    password: "kL6%?1LlF'AUMh",
  },
  {
    email: "rmurrison2j@toplist.cz",
    studentName: "Rennie",
    studentId: "53808-0692",
    studentClass: "Quechua",
    password: "wQ2%E1+RNK>!OW*",
  },
  {
    email: "mbrabon2k@shutterfly.com",
    studentName: "Morgan",
    studentId: "12634-171",
    studentClass: "Portuguese",
    password: "iE3}n>IHD>9y_SRH",
  },
  {
    email: "tmcgeaney2l@istockphoto.com",
    studentName: "Taddeusz",
    studentId: "49349-469",
    studentClass: "Kazakh",
    password: "fZ3$GyLxwU?.6t",
  },
  {
    email: "ugelling2m@indiegogo.com",
    studentName: "Udell",
    studentId: "0941-0457",
    studentClass: "Afrikaans",
    password: 'xO2*8!JV"94N',
  },
  {
    email: "jcuredell2n@vimeo.com",
    studentName: "Jone",
    studentId: "47593-469",
    studentClass: "Bulgarian",
    password: "fT8|Pzt&DDU~k'&",
  },
  {
    email: "amottinelli2o@blogs.com",
    studentName: "Annnora",
    studentId: "52567-001",
    studentClass: "Korean",
    password: 'yB5!sMh"`~',
  },
  {
    email: "idwight2p@alexa.com",
    studentName: "Inglis",
    studentId: "68820-107",
    studentClass: "Filipino",
    password: 'cY6"XbE60XBUEk\\',
  },
  {
    email: "rleyfield2q@usgs.gov",
    studentName: "Rolland",
    studentId: "60760-121",
    studentClass: "Papiamento",
    password: "rG4|4pn|a|",
  },
  {
    email: "spartington2r@businessinsider.com",
    studentName: "Sayres",
    studentId: "49035-030",
    studentClass: "Persian",
    password: "eR4=}R`?D.7'.t",
  },
];


const seedDatabase = async () => {
  try {
    // Connect to MongoDB without deprecated options
    await mongoose.connect(process.env.MONGO_DB_URL);

    console.log("Database connected");

    // Insert multiple student documents
    const result = await StudentModel.insertMany(students);
    console.log("Data seeded:", result);

    // Close the connection
    await mongoose.connection.close();
    console.log("Database connection closed");
  } catch (err) {
    console.error("Error seeding the database:", err.message);
  }
};

// Run the seed script
seedDatabase();
